#!/usr/bin/env python3
"""
holyc.py - HolyC Preprocessor and Compiler Driver for SecondDisplay.

Translates HolyC source (.HC) to standard C++ and compiles with MSVC (x64).
Handles HolyC types (U0, I64, U32, U8, Bool, etc.), memory functions
(MAlloc, Free, MemCpy, MemSet), HolyC string print statements, class declarations,
and recursive #include resolution.
"""

import os
import sys
import re
import argparse
import subprocess

PRELUDE = """// Generated by holyc.py - HolyC to C++ transpiler
#ifndef _CRT_SECURE_NO_WARNINGS
#define _CRT_SECURE_NO_WARNINGS
#endif
#ifndef _WINSOCK_DEPRECATED_NO_WARNINGS
#define _WINSOCK_DEPRECATED_NO_WARNINGS
#endif
#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#endif

#include <windows.h>
#include <winsock2.h>
#include <ws2tcpip.h>
#include <d3d11.h>
#include <dxgi1_2.h>
#include <mfapi.h>
#include <mfidl.h>
#include <mferror.h>
#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <shellapi.h>

#pragma comment(lib, "kernel32.lib")
#pragma comment(lib, "user32.lib")
#pragma comment(lib, "gdi32.lib")
#pragma comment(lib, "ws2_32.lib")
#pragma comment(lib, "ole32.lib")
#pragma comment(lib, "shell32.lib")
#pragma comment(lib, "mfplat.lib")
#pragma comment(lib, "mfuuid.lib")
#pragma comment(lib, "mf.lib")
#pragma comment(lib, "d3d11.lib")
#pragma comment(lib, "dxgi.lib")
#pragma comment(lib, "windowsapp.lib")

// HolyC basic types
typedef void U0;
typedef int8_t I8;
typedef uint8_t U8;
typedef int16_t I16;
typedef uint16_t U16;
typedef int32_t I32;
typedef uint32_t U32;
typedef int64_t I64;
typedef uint64_t U64;
typedef float F32;
typedef double F64;
typedef bool Bool;

#ifndef TRUE
#define TRUE true
#endif
#ifndef FALSE
#define FALSE false
#endif

// HolyC built-in functions
struct HolyCMAlloc {
    size_t sz;
    HolyCMAlloc(size_t s) : sz(s) {}
    template<typename T>
    operator T*() const { return (T*)malloc(sz); }
};
#define MAlloc(sz) HolyCMAlloc(sz)
#define Free(p) free((void*)(p))
#define MemCpy(d, s, n) memcpy((void*)(d), (const void*)(s), (size_t)(n))
#define MemSet(d, c, n) memset((void*)(d), (int)(c), (size_t)(n))
#define Print(...) do { printf(__VA_ARGS__); fflush(stdout); } while(0)

"""

MAIN_ENTRY = """
int WINAPI WinMain(HINSTANCE hInstance, HINSTANCE hPrevInstance, LPSTR lpCmdLine, int nCmdShow) {
    (void)hInstance; (void)hPrevInstance; (void)lpCmdLine; (void)nCmdShow;
    if (AttachConsole(ATTACH_PARENT_PROCESS)) {
        freopen("CONOUT$", "w", stdout);
        freopen("CONOUT$", "w", stderr);
    }
    Host_Main();
    return 0;
}

int main(int argc, char **argv) {
    (void)argc; (void)argv;
    Host_Main();
    return 0;
}
"""

def preprocess_holyc(source_file, visited=None):
    if visited is None:
        visited = set()

    abs_path = os.path.abspath(source_file)
    if abs_path in visited:
        return ""
    visited.add(abs_path)

    base_dir = os.path.dirname(abs_path)
    with open(abs_path, "r", encoding="utf-8", errors="replace") as f:
        lines = f.readlines()

    processed_lines = []
    has_host_main_invoc = False

    for line in lines:
        # Check for #include "..." of other HolyC files
        inc_match = re.match(r'^\s*#include\s*["<]([^">]+)[">]', line)
        if inc_match:
            inc_target = inc_match.group(1)
            target_path = os.path.join(base_dir, inc_target)
            if os.path.exists(target_path) and (target_path.endswith('.HC') or target_path.endswith('.hc') or target_path.endswith('.h')):
                inlined = preprocess_holyc(target_path, visited)
                processed_lines.append(f"// --- Inlined from {inc_target} ---\n")
                processed_lines.append(inlined)
                processed_lines.append(f"// --- End {inc_target} ---\n")
                continue
            else:
                # System include or not found locally
                processed_lines.append(line)
                continue

        # Check for top-level Host_Main; invocation
        if re.match(r'^\s*Host_Main\s*;\s*$', line) or re.match(r'^\s*Host_Main\s*\(\s*\)\s*;\s*$', line):
            has_host_main_invoc = True
            continue

        # HolyC _extern functions: _extern func_name ret_type (args); -> extern "C" ret_type func_name(args);
        extern_match = re.match(r'^\s*_extern\s+([A-Za-z0-9_]+)\s+([A-Za-z0-9_* ]+?)\s*\((.*?)\);', line)
        if extern_match:
            fn_name = extern_match.group(1).strip()
            ret_type = extern_match.group(2).strip()
            args = extern_match.group(3).strip()
            line = f'extern "C" {ret_type} {fn_name}({args});\n'
            processed_lines.append(line)
            continue

        # HolyC string statements: e.g. "format %d\n", arg1, arg2; -> Print("format %d\n", arg1, arg2);
        # Handle lines starting with optional whitespace and a string literal
        str_stmt_match = re.match(r'^(\s*)("([^"\\]|\\.)*"(?:[^;]*));\s*$', line)
        if str_stmt_match:
            indent = str_stmt_match.group(1)
            body = str_stmt_match.group(2)
            line = f"{indent}Print({body});\n"
        else:
            # Also handle inline string statement after if (...) "msg\n";
            inline_match = re.match(r'^(\s*(?:if\s*\([^)]+\)|else)\s+)("([^"\\]|\\.)*"(?:[^;]*));\s*$', line)
            if inline_match:
                prefix = inline_match.group(1)
                body = inline_match.group(2)
                line = f"{prefix}Print({body});\n"

        # HolyC class -> struct
        line = re.sub(r'\bclass\b', 'struct', line)

        processed_lines.append(line)

    content = "".join(processed_lines)
    return content

def compile_holyc(source_file, output_exe, vcvars_path=None, c_only=False, verbose=False):
    abs_src = os.path.abspath(source_file)
    src_dir = os.path.dirname(abs_src)
    root_dir = os.path.abspath(os.path.join(src_dir, "..", ".."))

    if not output_exe:
        output_exe = os.path.join(root_dir, "build", "host-holyc", "SecondDisplay.Host.HolyC.exe")
    output_exe = os.path.abspath(output_exe)

    out_dir = os.path.dirname(output_exe)
    os.makedirs(out_dir, exist_ok=True)

    cpp_file = os.path.join(out_dir, "holyc_transpiled.cpp")

    if verbose:
        print(f"[holyc.py] Preprocessing {source_file} -> {cpp_file}")

    body = preprocess_holyc(abs_src)

    # Combine PRELUDE + transpiled body + MAIN_ENTRY
    full_source = PRELUDE + body + MAIN_ENTRY

    with open(cpp_file, "w", encoding="utf-8") as f:
        f.write(full_source)

    if verbose:
        print(f"[holyc.py] Written {len(full_source)} bytes to {cpp_file}")

    if c_only:
        print(f"[holyc.py] C++ source generated at: {cpp_file}")
        return 0

    # Locate vcvars64.bat
    default_vcvars = r"C:\Program Files (x86)\Microsoft Visual Studio\18\BuildTools\VC\Auxiliary\Build\vcvars64.bat"
    if not vcvars_path:
        vcvars_path = default_vcvars

    if not os.path.exists(vcvars_path):
        # Search other standard VS locations
        candidates = [
            r"C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\Build\vcvars64.bat",
            r"C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Auxiliary\Build\vcvars64.bat",
            r"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat",
            r"C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Auxiliary\Build\vcvars64.bat",
        ]
        for c in candidates:
            if os.path.exists(c):
                vcvars_path = c
                break

    if not os.path.exists(vcvars_path):
        print(f"[holyc.py] Error: vcvars64.bat not found at {vcvars_path}", file=sys.stderr)
        return 1

    obj_file = os.path.join(out_dir, "holyc_transpiled.obj")
    cmd = f'call "{vcvars_path}" >nul && cl /nologo /O2 /W3 /TP /D_CRT_SECURE_NO_WARNINGS /Fo"{obj_file}" /Fe"{output_exe}" "{cpp_file}" /link /SUBSYSTEM:WINDOWS windowsapp.lib d3d11.lib dxgi.lib user32.lib gdi32.lib ole32.lib ws2_32.lib mfplat.lib mfuuid.lib /MANIFEST:EMBED "/MANIFESTUAC:level=\'asInvoker\' uiAccess=\'false\'"'

    if verbose:
        print(f"[holyc.py] Executing: {cmd}")

    res = subprocess.run(cmd, shell=True)
    if res.returncode != 0:
        print(f"[holyc.py] Compilation failed with code {res.returncode}", file=sys.stderr)
        return res.returncode

    print(f"[holyc.py] Successfully built: {output_exe}")
    return 0

def main():
    parser = argparse.ArgumentParser(description="HolyC Preprocessor & Compiler")
    parser.add_argument("input", help="Path to main HolyC source file (e.g. src/host.HC)")
    parser.add_argument("-o", "--output", help="Output executable path")
    parser.add_argument("--vcvars", help="Path to vcvars64.bat")
    parser.add_argument("--c-only", action="store_true", help="Generate C++ file only without compiling")
    parser.add_argument("-v", "--verbose", action="store_true", help="Verbose output")

    args = parser.parse_args()
    ret = compile_holyc(args.input, args.output, args.vcvars, args.c_only, args.verbose)
    sys.exit(ret)

if __name__ == "__main__":
    main()
